[package]
name = "fastbf"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/neodyland/brainfuck"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive", "env"] }

[build-dependencies]
anyhow = "1"
bindgen = "0.72.1"
cc = "1.2.57"

[profile.release]
strip = true
lto = true
codegen-units = 1

[features]
default = ["link"]
link = []